# Generated by Django 4.0 on 2022-01-19 07:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enjoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idnumber', models.CharField(max_length=100, unique=True, verbose_name='ID NO.')),
                ('Lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('MI', models.CharField(max_length=100, verbose_name='Middle Initial')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('contactnumber', models.CharField(max_length=11, verbose_name='Contact Number')),
                ('dateofbirth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('VMfirstdose', models.CharField(max_length=100, verbose_name='VM First Dose')),
                ('VMseconddose', models.CharField(max_length=100, verbose_name='VM Second Dose')),
                ('Sfirstdose', models.DateField(blank=True, verbose_name='Sched First Dose')),
                ('Sseconddose', models.DateTimeField(blank=True, verbose_name='Sched Second Dose')),
            ],
        ),
        migrations.CreateModel(
            name='PreRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Idnumber', models.CharField(max_length=100, unique=True, verbose_name='idnum')),
                ('user_Lname', models.CharField(max_length=100, verbose_name='LastName')),
                ('user_Fname', models.CharField(max_length=100, verbose_name='FirstName')),
                ('user_MI', models.CharField(max_length=100, verbose_name='MiddleInitial')),
                ('user_Address', models.CharField(max_length=100, verbose_name='Address')),
                ('user_contactnumber', models.CharField(max_length=11, verbose_name='ContactNumber')),
                ('user_dateofbirth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('user_VMfirstdose', models.CharField(max_length=100, verbose_name='VMFirstDose')),
                ('user_VMseconddose', models.CharField(max_length=100, verbose_name='VMSecondDose')),
                ('user_Sfirstdose', models.DateField(blank=True, verbose_name='SchedFirstDose')),
                ('user_Sseconddose', models.DateField(blank=True, verbose_name='SchedSecondDose')),
                ('VCphoto', models.ImageField(default='VCpic/image.jpg', upload_to=users.models.PreRegister.image_path)),
                ('user_Email', models.EmailField(default='Example@gmail.com', max_length=100, verbose_name='Email')),
            ],
        ),
    ]
