# Generated by Django 4.0 on 2022-01-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enjoyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enjoyer',
            name='contactnumber',
        ),
        migrations.RemoveField(
            model_name='enjoyer',
            name='dateofbirth',
        ),
        migrations.AlterField(
            model_name='enjoyer',
            name='Sseconddose',
            field=models.DateField(blank=True, verbose_name='Sched Second Dose'),
        ),
    ]
